apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-selec
  template:
    metadata:
      labels:
        app: app-selec
    spec:
      containers:
        - name: app-container
          image: christellaa/ci-cd-integration-img:v2
          ports:
            - containerPort: 8081
          imagePullPolicy: IfNotPresent